version: '3'
services:
  homeassistant:  # Home Assistent Container
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${HOMEASSISTENT_DOCKER_TAG}"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mosquitto:  # MQTT Broker Container
    image: "eclipse-mosquitto:${MOSQUITTO_DOCKER_TAG}"
    container_name: mosquitto
    volumes:
      - ./mqtt:/mosquitto
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
